spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true 

datasource:
  url: "jdbc:mysql://localhost:3306/ljelectrar"
  username: 
  password: 
  
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082